// <auto-generated />
namespace escuela.webapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateSP_Notas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateSP_Notas));
        
        string IMigrationMetadata.Id
        {
            get { return "202002150623368_CreateSP_Notas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
